### ISSUE TITLE
Figure out why schematic layout and circuit-to-svg are so big, reduce their size and update core

### ISSUE THREAD

**Issue by seveibar** [tscircuit/core#248]
These modules have dramatically increase core size, it looks like it's probably files being accidentally bundled, we should make sure they use `tsup-node` (not `tsup` which bundles dependencies) have have the `package.json` `"files"` defined properly

![Image](https://github.com/user-attachments/assets/fa566244-502a-4d8b-b695-6f8d8b60703d)

/bounty $15

**Comment by akhilender-bongirwar** [comment]
> ![Image](https://github.com/user-attachments/assets/fa566244-502a-4d8b-b695-6f8d8b60703d)

@seveibar, is there a way to generate this report locally to test changes ?

**Comment by seveibar** [comment]
@akhilender-bongirwar the package.json file should have a command that uses iirc `howfat`

**Comment by akhilender-bongirwar** [comment]
@seveibar, I actually tried `bun run measure-bundle` and encountered several warnings, causing the terminal to crash. This happened twice, which is why I reached out here.

![Image](https://github.com/user-attachments/assets/80c78fbf-4d08-43a0-b38b-554c1e096971)


> the package.json file should have a command that uses iirc howfat

However, after seeing your reply, I cloned the repository again and tried once more. This time, despite the warnings, the table was generated.



> you can always take a peek at the workflow that writes that comment as well inside the `.github/workflows` directory

The changes I made didn’t reduce the size, so I decided not to proceed under the issue.

Thank you for your response : )
